#!/bin/bash
echo "obase=$(echo "bestchol" | wc -c | bc -l | awk '{print $1-1}'); ibase=$(echo "water" | wc -c | bc -l | awk '{print $1-1}'); $(echo "$WATER" | tr 'water' '0-4') + $(echo "$STIR" | tr 'stir.' '0-4')" | bc | tr '0-8' 'bestchol'
